-- +goose UP 
CREATE TABLE users (
  id    UUID PRIMARY KEY, 
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  email   VARCHAR(255) UNIQUE NOT NULL
);

-- +goose Down
DROP TABLE users;
